name: 'Claude Code Review'
description: 'Automated code reviews using Claude AI'
author: 'Two Inc'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: false
  claude_code_oauth_token:
    description: 'Claude Code OAuth token (alternative to anthropic_api_key)'
    required: false
  track_progress:
    description: 'Enable visual progress tracking comments'
    required: false
    default: 'false'
  use_sticky_comment:
    description: 'Use sticky comments for consistent feedback across PR updates'
    required: false
    default: 'false'
  settings:
    description: 'Claude Code settings as JSON string or path to settings JSON file'
    required: false
  plugins:
    description: 'Newline-separated list of Claude Code plugin names to install'
    required: false
    default: 'two-database'
  plugin_marketplaces:
    description: 'Newline-separated list of Claude Code plugin marketplace Git URLs'
    required: false
    default: 'https://github.com/two-inc/agent-plugins.git'
  include_fix_links:
    description: 'Include Fix this links in PR code review feedback'
    required: false
    default: 'true'
  include_comments_by_actor:
    description: 'Comma-separated list of actor usernames to include in comment context'
    required: false
  exclude_comments_by_actor:
    description: 'Comma-separated list of actor usernames to exclude from comment context'
    required: false
  allowed_bots:
    description: 'Comma-separated list of bot usernames allowed to trigger reviews (use * for all bots)'
    required: false
    default: 'dependabot'
  github_app_id:
    description: 'GitHub App ID for generating a token with cross-repo access (e.g. for private plugin marketplaces)'
    required: false
  github_app_private_key:
    description: 'GitHub App private key for generating a token with cross-repo access'
    required: false
  prompt:
    description: 'Custom review prompt'
    required: false
    default: |
      REPO: ${{ github.repository }}
      PR NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}

      **Tool Reference** (use MCP tools as primary, GraphQL as fallback or where MCP lacks support):

      Reading:
      - PR details: `mcp__github__get_pull_request`
      - PR comments: `mcp__github__get_issue_comments`
      - Existing review comments: `mcp__github__get_pull_request_review_comments`
      - PR diff: `mcp__github__get_pull_request_diff`

      Writing (regular PRs - ALWAYS use inline review, NEVER top-level comments):
      - **PRIMARY**: `mcp__github__create_and_submit_pull_request_review` - submit a review with inline comments on specific lines. Every comment MUST include `path` (file path) and `line` (line number). Keep the review `body` empty or minimal - put ALL feedback in inline comments. When proposing a concrete code fix, use a ` ```suggestion ` block in the comment body so the author can apply it with one click
      - Replying to existing inline threads: `Bash(gh api graphql:*)` with addPullRequestReviewThreadReply mutation:
        ```
        gh api graphql -f query='mutation { addPullRequestReviewThreadReply(input: {pullRequestReviewThreadId: "THREAD_ID", body: "reply text"}) { comment { id } } }'
        ```
      - Resolving fixed threads: `Bash(gh api graphql:*)` with resolveReviewThread mutation:
        ```
        gh api graphql -f query='mutation { resolveReviewThread(input: {threadId: "THREAD_ID"}) { thread { id } } }'
        ```

      Writing (release PRs ONLY):
      - `mcp__github__add_issue_comment` - ONLY for release PR summaries. NEVER use this for regular PR reviews

      Fallback for any failed MCP operation: `Bash(gh api graphql:*)`

      **LINEAR_API_KEY Integration**:
      If LINEAR_API_KEY is available in the environment, create Linear issues for any significant problems or follow-up work that developers should address.

      **STEP 1 - Determine PR Type**:
      First, use `mcp__github__get_pull_request` to read the PR title, description, and branch names to determine if this is a release PR.

      **Release PR Detection**:
      A PR is a release PR if ANY of these match:
      - Branch name starts with `release/` or `releases/`
      - PR title starts with "Release" or matches pattern "v[0-9]+\.[0-9]+"
      - PR is merging a release branch (release/*, releases/*) into main/master
      Do NOT treat as a release PR just because the word "version", "bump", or "tag" appears somewhere in the title or description - these often appear in regular PRs (e.g. "bump lodash version").

      **For Release PRs**: Create a release summary instead of a detailed review:
      1. **MANDATORY - Check for existing summaries**: Use `mcp__github__get_issue_comments` to read all PR comments and see if a release summary already exists
      2. **NEVER duplicate summaries**: If a release summary comment already exists, DO NOT create another one
      3. **Read all commits**: Use the diff and commit history to understand every change included in the release
      4. **Create release summary**: Use `mcp__github__add_issue_comment` to post a summary using EXACTLY this format:

      ```
      ## Release Summary

      ### Breaking Changes
      - Description of breaking change with migration steps (#PR)

      ### Features
      - Description of new feature (#PR)

      ### Fixes
      - Description of bug fix (#PR)

      ### Improvements
      - Description of improvement (#PR)

      ### Dependencies
      - Upgraded/added/removed dependency X from vA to vB (#PR)

      ### Database Migrations
      - Description of schema change (#PR)
      ```

      Rules for the release summary:
      - Only include sections that have entries - omit empty sections entirely
      - Every item MUST link to the relevant PR number as `(#123)`
      - Breaking Changes section always comes first if present
      - Database Migrations section must be included whenever Alembic migrations are part of the release
      - Keep descriptions concise - one line per change
      - Group related changes into a single bullet rather than listing each commit separately

      5. **Do NOT create a review**: Skip the normal review process entirely

      **For Regular PRs**: Follow normal review process with extreme selectivity:

      1. **Read existing reviews**: Use `mcp__github__get_pull_request_review_comments` AND `mcp__github__get_issue_comments` to read ALL existing comments from Claude and other reviewers. Note what Claude has already reviewed and what issues anyone has flagged.

      2. **Check if action is needed**:
         - If Claude already posted a review and no significant new commits since → exit without posting
         - If significant new commits exist → re-review the full diff (not just new commits — they may interact with earlier changes)
         - "Significant" = changes to application code, migrations, API contracts, or configuration. Doc/comment/formatting/CI-only commits are not significant

      3. **Get diff**: Use `mcp__github__get_pull_request_diff`

      4. **Resolve fixed issues**: If Claude previously flagged issues that are now fixed, resolve those threads via `resolveReviewThread` mutation

      5. **Submit review** via `mcp__github__create_and_submit_pull_request_review`:
         - **NEVER use event type "APPROVE" or "REQUEST_CHANGES"** — always use "COMMENT". You assist human reviewers; they make the final approval decision
         - If you have critical findings: include inline comments and recommend against merging
         - If all previously flagged issues are addressed: note they're resolved and recommend the PR is ready for human approval
         - If first review with no critical issues: briefly note no critical issues found

      **ONLY flag these critical issues:**
      - Security vulnerabilities (SQL injection, XSS, auth bypasses, etc.)
      - Critical bugs causing runtime failures, data corruption, or crashes
      - Memory leaks or severe performance bottlenecks
      - Breaking API changes
      - Data loss risks or unsafe database operations
      - Unsafe database migrations (see migration review below)

      Do NOT comment on: style, formatting, naming, subjective preferences, non-critical optimisations, documentation, or code that works but could be "better". When in doubt, don't comment.

      **Database Migration Review (Alembic/PostgreSQL)**:
      For PRs with Alembic migration files (under `alembic/versions/` or `migrations/versions/`), use the `two-database` plugin's `alembic-postgres-migration-helper` skill and run: `Bash(python ${CLAUDE_PLUGIN_ROOT}/two-database/scripts/validate_migration.py <migration_file>)`
      Check for: missing lock timeouts, non-concurrent index creation, backwards-incompatible changes without expand-migrate-contract, missing NOT VALID on FK constraints, FOR UPDATE SKIP LOCKED.

      **Rules:**
      - All feedback MUST be inline comments with `path` and `line`. Never use `mcp__github__add_issue_comment` for regular PRs. If you can't tie feedback to a specific line, don't post it
      - Never duplicate a comment already made by Claude or another reviewer
      - Maximum 3 inline comments per PR unless there are genuine security/critical issues
      - Use ` ```suggestion ` blocks when proposing concrete code fixes (set both `start_line` and `line` for multi-line replacements). Don't use suggestion blocks for general warnings without a single concrete fix
  extra_prompt:
    description: 'Additional instructions to append to the base prompt'
    required: false
    default: ''
  claude_args:
    description: 'Additional Claude CLI arguments'
    required: false
    default: '--max-turns 15 --allowedTools "mcp__github__get_pull_request,mcp__github__get_pull_request_reviews,mcp__github__get_issue_comments,mcp__github__get_pull_request_diff,mcp__github__get_pull_request_files,mcp__github__get_pull_request_review_comments,mcp__github__create_and_submit_pull_request_review,mcp__github__add_issue_comment,mcp__github_inline_comment__create_inline_comment,Write,Bash(cat *),Bash(grep *),Bash(gh api graphql:*),Bash(gh api repos/*),Bash(python *validate_migration*)"'

outputs:
  session_id:
    description: 'Claude Code session ID for resuming conversation'
    value: ${{ steps.claude-review.outputs.session_id }}
  structured_output:
    description: 'Structured JSON output from Claude'
    value: ${{ steps.claude-review.outputs.structured_output }}
  execution_file:
    description: 'Path to execution output file'
    value: ${{ steps.claude-review.outputs.execution_file }}

runs:
  using: 'composite'
  steps:
    - name: Generate GitHub App token
      id: app-token
      if: ${{ inputs.github_app_id != '' && inputs.github_app_private_key != '' }}
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.github_app_id }}
        private-key: ${{ inputs.github_app_private_key }}
        owner: ${{ github.repository_owner }}

    - name: Configure git auth for private marketplace
      if: ${{ steps.app-token.outputs.token != '' }}
      shell: bash
      run: git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"

    - name: Setup GitHub CLI
      shell: bash
      run: |
        if ! command -v gh &> /dev/null; then
          echo "Installing GitHub CLI..."
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
        fi
        gh --version

    - name: Run Claude Code Review
      id: claude-review
      uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        track_progress: ${{ inputs.track_progress }}
        use_sticky_comment: ${{ inputs.use_sticky_comment }}
        settings: ${{ inputs.settings }}
        plugins: ${{ inputs.plugins }}
        plugin_marketplaces: ${{ inputs.plugin_marketplaces }}
        include_fix_links: ${{ inputs.include_fix_links }}
        include_comments_by_actor: ${{ inputs.include_comments_by_actor }}
        exclude_comments_by_actor: ${{ inputs.exclude_comments_by_actor }}
        allowed_bots: ${{ inputs.allowed_bots }}
        prompt: |
          ${{ inputs.prompt }}

          ${{ inputs.extra_prompt }}
        claude_args: ${{ inputs.claude_args }}
